### ISSUE TITLE
Ticket #07: When the page is refreshed, the filled out info is still there.

### ISSUE THREAD

**Issue by blancaum** [Adalab/project-promo-r-module-2-team-1#23]
Have the content stored in the browser's LocalStorage.

**Comment by blancaum** [comment]
Esto tiene que hacerse a partir del día 8 que es cuando tenemos la clase.

**Comment by lauragonzalezcalvo** [comment]
- [ ] Faltaría poner el link generado en nuestro enlace a twitter.
- [ ] Mostrar lo guardado en el localStorage en el HTML.
- [ ] Revisar que la primera paleta aparece como seleccionada pero cuando relleno los campos me pone que tengo que rellenarlos.
