### ISSUE TITLE
1. Awesome Profile Cards UI. MOBILE.

### ISSUE THREAD

**Issue by blancaum** [Adalab/project-promo-r-module-2-team-1#4]
**To do HTML:** 

- [x]  Landing page
- [x]  Header
- [x]  Mobile layout
- [x]  Colapsable form: DISEÑA
- [x]  Colapsable form: RELLENA
- [x]  Colapsable form: COMPARTE
- [x]  Card preview
- [x]  Footer

 **To do Sass**

- [x]  Landing page
- [x]  Header
- [x]  Mobile layout
- [x]  Colapsable form: DISEÑA
- [x]  Colapsable form: RELLENA
- [x]  Colapsable form: COMPARTE
- [x]  Card preview
- [x]  Footer

**Comment by marocena26** [comment]
20-10: create partials HTML and Sass.

**Comment by marocena26** [comment]
**21-10:** 

- create branch (footer, header, form, landing-index)
- merge (lunes)
- JS partials (miércoles)

**Comment by marocena26** [comment]
24-10: 
- Merge de todas las ramas.
- Solucionar problemas con Packet-JS.
- Terminada parte HTML y Sass.
