### ISSUE TITLE
Ticket #08: Review height of the landing, it is too big

### ISSUE THREAD

**Issue by blancaum** [Adalab/project-promo-r-module-2-team-1#41]
**Nota: Hay que hacer una nueva rama para este ticket :)**

Se queda así y no puedes hacer scroll

![Image](https://user-images.githubusercontent.com/13077932/199812602-9f0f758d-b7ed-4a33-873c-1ff6e3a653a1.png)

**Comment by marocena26** [comment]
Modificado:
- **header:** se ha metido dentro del main con un ` include`.
- **footer:** se ha creado un mixin (ahorrar código) para que el footer del landin sea distinto al footer del preview:
    - el footer del landing **tienen fixed.**
    - el footer del preview no.

-Se ha modificado el **HTML** del landing para añadir dos cajas más y poder dar los estilos correctos.
