### ISSUE TITLE
Think about the personalization of the page

### ISSUE THREAD

**Issue by blancaum** [Adalab/project-promo-r-module-2-team-1#48]
Pensar alguna idea de logos, temática, colores, etc. y ponerla [en el excel, en la pestaña de "Ideas para personalizar la página"](https://docs.google.com/spreadsheets/d/1qnnyNCVSOodUCRQ20rbVB3BxPZdExEWLAS6vvxmuN-k/edit?usp=sharing).

**Comment by marocena26** [comment]
- Web para un público profesional: más aséptica, con colores básicos y de foto la imagen de alguien de "oficina".
- Web más animada con estilos básados en la serie de animacion de Gravity Falls. Colores más llamativos (rosas, morados, amarillos)

**Comment by blancaum** [comment]
Revisarlo el jueves 10 de noviembre (siempre que hayamos terminado lo de la API)
